
title: FoMo-HRI
description: Human – Foundational Model Interaction
show_downloads: false
google_analytics:
email_address: d.hernandez_garcia@hw.ac.uk #daniel.hernandezgarcia@manchester.ac.uk



show_excerpts: true

repository: dhgarcia/human-llm-interaction

# With GitHub Pages Gem
# remote_theme: chrisrhymes/bulma-clean-theme
remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0

theme_color: '#361111'